[package]
name = "dialect"
version = "0.0.1"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "dialect"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.17.0"